#!/bin/bash

for i in {2..9}
do
  Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K$i $i 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K$i.log
done



Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K3 3 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K3.log

Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K4 4 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K4.log

Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K5 5 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K5.log

Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K6 6 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K6.log

Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K7 7 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K7.log

Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K8 8 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K8.log

Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K9 9 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K9.log

Rscript ./canopy.R /home/pgm/Workspace/MPM/VCF_finaux/falcon/patient_5009/ 5009 B00JAJB B00JAJC /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJB.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/VCF_finaux/somatic_sandbox/M662_DA_5009_T_B00JAJC.normalized.vcf_multianno.hg38_multianno.txt /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJB.other_tumor_positions.vcf /home/pgm/Workspace/MPM/scripts_colbalt/calling_somatic_genotype/output/M662_DA_5009_T_B00JAJC.other_tumor_positions.vcf /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/5009.K10 10 2>&1 | tee /home/pgm/Workspace/MPM/marathon/canopy/generated_clustering/5009/execution_K10.log
